### ISSUE TITLE
university selector broken

### ISSUE THREAD

**Issue by algnor** [tumble-dev/Tumble-Cross-Platform#160] opened 2023-10-10 23:38 UTC
The university selector seems very broken at the moment (at least for me)

Phone: Sony Xperia 1 III
Android: 13

Steps
1. Clear app cache/storage
2. Start app
3. Select Mälardalens university
4. Nothing happens

Other universities seem to work.
Changing schools has the same problem, except choosing a school _**might**_ look like it worked, but it never actually changed. And additionally now all the schools will behave the same as MDU (nothing happens) 

Reinstall also doesn't help.

I am fairly sure the latest Google play version (8 Oct) caused this.

This app is genuinely fantastic, so I would love to be able to use it again.

I have no experience with flutter so I cannot help code-wise, but Incase this is something specific to my configuration I will gladly provide logs etc.

As a side note the app still displays "Mälardalens högskola" instead of "Mälardalens universitet"

**Comment by adisve** [comment] 2023-10-10 23:56
Thanks for the feedback!

We will try fixing this as soon as possible. Sorry for the inconvenience, as we simply updated the app SDK version and assumed the app would keep working fine.

**Comment by adisve** [comment] 2023-10-11 09:58
I believe the issue is resolved with the university selection and I will release this new version as soon as possible. The problem you faced with the state of the school name not being updated in the settings drawer is just a state problem and not something we will be fixing right now, as this would require a larger remake of the app. Since we are in the middle of making a native version for android this wouldn't be worth it, as we are only two people on the project.

**Closed as completed** 2023-10-13 05:33 UTC
